lexik_jwt_authentication:
    secret_key: "kernel.project_dir %/jwt/private.pem " #required for token creation
    public_key: "kernel.project_dir %/jwt/public. pem " #required for token verification
    pass_phrase: "your_secret_passphrase " # required for token creation
    token_ttl: 86400
